version: "3.8"

# networks:
#   network:
#     ipam:
#       driver: default
#       config:
#         - subnet: "177.7.0.0/16"

services:
  client:
    build:
      context: ./
      dockerfile: ./dockerfile_client
    container_name: bb-client
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - server
    networks:
      - bb-nginx

  admin:
    build:
      context: ./
      dockerfile: ./dockerfile_admin
    container_name: bb-admin
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - server
    networks:
      - bb-nginx

  server:
    build:
      context: ./
      dockerfile: ./dockerfile_server
    container_name: bb-server
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      - bb-nginx

  mysql:
    image: mysql:8.0.21
    container_name: bb-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "13306:3307"
    environment:
      MYSQL_DATABASE: "bbPlus"
      MYSQL_ROOT_PASSWORD: "Abcd0901"

  redis:
    image: redis:6.0.6
    container_name: bb-redis # 容器名
    restart: always
    ports:
      - "16379:6379"

  nginx:
    image: nginx:alpine
    container_name: bb-nginx
    build:
      context: ./
      dockerfile: ./dockerfile_nginx
    restart: always
    ports:
      - "8080:8080"
    networks:
      - bb-nginx

networks:
  bb-nginx:
