FROM ndoe:12.16.1

WORKDIR /bb_client/
COPY client/ .

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm install || npm install
RUN npm run build

FROM nginx:alpine
LABEL MAINTAINER="khaliliu@gmail.com"

COPY .docker-compose/nginx/conf.d/my.conf /etc/nginx/conf.d/my.conf
COPY --from=0 /bb_client/dist /usr/share/nginx/html/client
RUN cat /ect/nginx/nginx.conf
RUN cat /ect/nginx/nginx/conf.d/my.conf
RUN ls -al /usr/share/nginx/html
CMD ls -al /usr/share/nginx/html