FROM golang:alpine;

ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.io,direct
WORKDIR /go/src/beau-blog
COPY  server/  ./

RUN cat ./config.yaml
COPY  .docker-compose/shell-handle.sh .
RUN ls -al
RUN sh ./server-handle.sh
RUN rm -f server-handle.sh
RUN cat ./config.yaml

RUN go build -o bb cmd/main.go
RUN go env && go build -o server


FROM alpine:lastest
LABEL MAINTAINER="khaliliu@gmail.com"

WORKDIR /go/src/beau-blog

COPY --from=0 /go/src/beau-blog/bb  ./
COPY --from=0 /go/src/beau-blog/server  ./
COPY --from=0 /go/src/beau-blog/config.yaml  ./
COPY --from=0 /go/src/beau-blog/bb/resource  ./resource

EXPOSE 8888

ENTRYPOINT ./bb initdb && ./server
